image: node:18-alpine
options:
  docker: true
pipelines:
  branches:
    release/dockerhub/dev:
      - step:
          name: create and Push Docker Image
          script:
            - docker login -u $docker_username -p $docker_password
            - docker build -t globalvox/escrow-api-server:$build_tag .
            - docker push globalvox/escrow-api-server:$build_tag